apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kube-prometheus-stack
  namespace: monitoring
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
        path: /monitoring
        pathType: Prefix 