apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: network-metrics-database
  namespace: databases
spec:
  instances: 3

  monitoring:
    enablePodMonitor: true
  
  bootstrap:
    initdb:
      database: network-metrics
      owner: network-metrics
      secret:
        name: network-metrics-database-creds
  
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem