apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
  namespace: databases
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: network-metrics-database
  namespace: databases
spec:
  instances: 3

  bootstrap:
    initdb:
      database: network-metrics
      owner: network-metrics
      # secret:
      #   name: network-metrics-database-creds
      secret:
        name: app-secret

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem