apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: databases
spec:
  instances: 3

  monitoring:
    enablePodMonitor: true
  
  inheritedMetadata:
    labels:
      app: cnetwork-metrics-database

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  
  storage:
    storageClass: standard
    size: 1Gi
