apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: network-metrics-db
spec:
  description: Postgres cluster for network-metrics
  imageName: quay.io/enterprisedb/postgresql:17.4

  bootstrap:
    initdb:
      database: networkmetricsdb
      owner: networkmetricsdb
      secret:
        name: network-metrics-db-secret