apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: databases
spec:
  instances: 3

  monitoring:
    enablePodMonitor: true
  
  inheritedMetadata:
    labels:
      app: cnetwork-metrics-database
  
  storage:
    size: 1Gi
