---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: network-metrics-database-creds
  namespace: databases
spec:
  encryptedData:
    password: AgCYk9GV6zGf49M5UrhT65UpepE6jjANGVtGlhiC66lMbXMAuoKm/oH9IFKrGC5ynPGr2YoJ8YoF/+PKmqzMY3Ug147IgaVdVX3rfXWBSKQOVcSQfJc2n+F6Z5omH5Oa47/awz59IGspUUsC3I6YsRmu+ouVJkT619XhzOD49K6yYpjNFmzgorgxAnsj6JlVxosa/eLJEIA2YUkYSUMBTejirhjHkKegicsHpF+ZyOvIhIZURoNft9K/vUkF7L6Pdie3I4qCIT8YHqzfglda+gz8MlXoGR75PspVZbtfZQLeKZTwCYlods2dov01qinOA18EkzEL8TJ/cpePOf1Ty3MT2Tily1iN0aE8HQifLN5It+yBpSQl/TlkT1m3jyQjNdpUk8O+hPXrQgtBKtI1vnQZuwRG+1emxmHy8ncep9ubhHKElprwQ38rqW04WpLIef8boijh1tNgtcZx7DOgLK+wseHJ56JygWdZjcdITdbnUMhvCBVRHyGI8cgoWHz93hnwqtfzzMxfUvovvQgE1vYWe+DsaWDkbp6pMURpDt02gJmK7aBFZ3AllZBzr6alY78f3frNtO5KjoGIvVa7iU9WnEegg76a1MIsTjs6E5KewpTeELv76UUfFrdPyz7yQewzkfKZGHR+sEw4cWo8xi1ur+T8xdUHfQq9hzCtHIldpEXrSt/b6LoFJonXg+fKcH+vs7fiOuETBS4QtiV+vBGMIgG51w==
    username: AgC/ZqURSnzL36PgH27DpApO8BMxy2NYmNa/hkgFHcisky6lX8zENe5AXnInzPmt/l/d4koKnA3Bd308Th3DKnaU1flxUBAJflpVLpnUgd6IOhvcIMVTQkdIKH5LjMKT7Voe1to7MaPPs3m3nkEu7zqhQLHIGAXDkqKwHDDoLIqUzGLeVG/lp4L5PV+o2bse6Fq41LoqBJMsCz6j7fo49GHhBwuyA9aMiaBpqvkMGmP0f80e83lyuqzGbK3kXIEv6W9obdmUhz7rkZMljo4MrhThAZ059mvERU8RUWq0gDs6fMxh9UD3+giHaHDFQzRSA/fW8Voqwhxhbb001BoqaFGp+xb1DGSN+a5tFJ+vLGug2m48zJ2lmsBxUrpm2syZQwsGv098he2J0rbnaJaZsIUofdBt6E+1r8c+l8kQghT49D3TjCYnsDTOEAb4kap0NFvxXYaTqTF+jAqlOIxMcmBj8bFmH9MQPiX1DXtRFCah6lnFuCNxvKkLbJl6AmGUETQ6T2SZqIeAssTcVxH2l7Y55BdcDuzssg6ovnuYpsznryEbyISeiBYEUXH3XtPKcywWW+R903D2ISoTsHDmsveHjvsPaQTU03AYMk28NyhSBce5pTHq6RMVkPdggFmxkJzq8aWuBxYCjq53coUmiSmBrC/hLq/qStW+LgWhSXuBLP3dsoOH8s5BmP8SvWEF7kREl10FIRh/4ZI7lOlSM2E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: network-metrics-database-creds
      namespace: databases
