---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: network-metrics-database-creds
  namespace: databases
spec:
  encryptedData:
    password: AgCY51nm6fBhseKGT7t4HBNhtvtS7JRRCq37sg4DbK/Fzpv/q2fcphe4FwZCoV9cDubS+bUPXuQCKbZrFerZ7qk2VgL/u/XIhNmxSNMnv+LER7kHtQnZZmoelRBIvTSF9JAFnRrSQnBQNsDjLFF+4eh1+mzAKXqkql+i7Pd9IBIEX
QGiezNw9vmhvqqexmmJAXwHu5/QM2lH+ZL0Cu1ilKWuzYAbV1X3fkkwKFMuMn1UZPBVl1pV00VQ94fc9B1OYjXDMxFrTpnzsod2aGg2vSgWYz1OJ8Xx7xlk5XL7RfshDkGG+U8FHqE5M8S8jRTmK7aKv28/NeSs7c1o/OdhShWzb3vz7E1XaIjARvhs
rQzpjDQDZi0Y5GgT49euWWiL++sLUlPaRffhm0nsvvuIAgalOXbtbrtluOUEaZUVBp+5YrKPKEEUqg49UgilxtC4wvKJ3p9Xv0HM3qvJuaPUZV1qJqarxa3tU6A5zndbFyDGfZcUi7TMujbSZRaq34s5KwYvkEhYpbLprGJJNgHE2LMhnuU3bi+JSPk
dfhSpaYRFsSnqiqPYuZNnWGw1VQodvqIqtHsqoAPpE0AeGy0plk+2KHZLomrng8FrG2pS50zSUfvHWzEkxTEb3aj0MqN3BHKFiaJwPRrR7zY0cDcA1gQ7VXLPy8Vi3a5Pn6X2Am1TSVMw8UHJlKGu1Ycx/IJQYopOvT0L7PhAcRjGGJNlwM/+VAFGJQ
==
    user: AgBbrARJ8ifrUTwRrz2CGmC/b8vAi7e6wereQupbghLopTPBeZwIiBsjZqlQvckkX3jqfSLC9cPQUHH9+KJQ4hYyroMH7EH/J9kJhqkLKwyztCMSR2zA+PNVaj8RnjsZzB2nnK/h0NaRWjKOnSL7fnTVQ+C7U7FO1hzNrSy3eJ2qwPURx
+TCsquOk8aUcjPk0o+NghxR3RgmoI9ehI0SonF6ReEQWPDIJZY2jc/POtVlOuv6T/qECtc+fJq2cm0gMSZ1dG7Ae5lcc8JGsBteP4M3CIKcYOlFKn70LmZkx36nD22di73NYayy5ioILUaI1kwm8+iMc9UsWlpTfQm1PNOTCuoTejcGMUFYe0A7j/ky
5uPuufk0M1Sp1R/DaFSaK8bNLfDoVCU34UeuYTag3BKxT4yQUqfNLOi5AUwFPglc18+27MmMwIFad6YTq9e3r/GZstBUR4WWeqAFAPA7nR/rvfDfG/fvRswAOu0rCzUGbYzTIDsJI6s8NrryKpSnXB4ol/Qj8+z7A2P6DAc+BBovnQeKvL0KY+uFtGS
TxXw9CpkuXZsuPEXWLOdgvY+liumH89DGP/FKNYELoclDHZ1FSMRNAmiDJNJZx8+cY8N8SNUkJsksCNwvbrzGPPXAu7+lxzz19Imyr6y0iQHL+Srt1D2fWUw+dJQN1aDAG3BEZDYypW867FRu+ElxRkhRCzMTl1YUdw==
  template:
    metadata:
      creationTimestamp: null
      name: network-metrics-database-creds
      namespace: databases