# Flux HelmRelease to grab Cilium ingress controller chart + install the Ingress
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system

spec:
  releaseName: cilium
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.17.x
      interval: 6h
      sourceRef:            
        kind: HelmRepository  
        name: cilium
        namespace: kube-system

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values