# Flux Helm repository for installing stuff from Cilium (e.g. Cilium ingress controller)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  url: https://helm.cilium.io/