# Kustomization custom resource to load resource located in the apps folder

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  # dependsOn: 
  #   - name: infrastructure
  interval: 5m0s
  retryInterval: 1m
  path: ./fluxcd/databases/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
