# Kustomization custom resource to load resource located in the apps folder

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/infrastructure/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
