# Kustomization custom resource to load resource located in the apps folder

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: monitoring
spec:
  # dependsOn: 
  #   - name: infrastructure
  interval: 5m0s
  path: ./fluxcd/monitoring/controllers/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
