apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
  blocks:
    - start: "192.168.1.50"
      stop: "192.168.1.75"
