# Flux HelmRelease to grab Cilium ingress controller chart + install the Ingress
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system

spec:
  releaseName: cnpg
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.x
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system